query_seq_classif = '''SELECT DISTINCT
	   AP.NR_ATENDIMENTO,
	   AP.NR_SEQ_CLASSIFICACAO,
       AP.CD_ESTABELECIMENTO
FROM TASY.ATENDIMENTO_PACIENTE AP
    INNER JOIN TASY.ATEND_PACIENTE_UNIDADE APU ON AP.NR_ATENDIMENTO = APU.NR_ATENDIMENTO
    INNER JOIN TASY.SETOR_ATENDIMENTO SA ON APU.CD_SETOR_ATENDIMENTO = SA.CD_SETOR_ATENDIMENTO
    INNER JOIN TASY.ESTABELECIMENTO ON ESTABELECIMENTO.CD_ESTABELECIMENTO = AP.CD_ESTABELECIMENTO
    INNER JOIN TASY.EMPRESA ON EMPRESA.CD_EMPRESA = ESTABELECIMENTO.CD_EMPRESA
WHERE EMPRESA.CD_EMPRESA = 1 AND ESTABELECIMENTO.CD_ESTABELECIMENTO IN (1, 34) 
AND AP.IE_TIPO_ATENDIMENTO = 3 
AND AP.DT_ENTRADA >= TO_DATE('{data_ini}', 'DD/MM/YYYY')
AND AP.DT_ENTRADA < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY '''

query_cancelamento = '''SELECT DISTINCT
	   AP.NR_ATENDIMENTO,
	   AP.DT_CANCELAMENTO 
FROM TASY.ATENDIMENTO_PACIENTE AP
    INNER JOIN TASY.ATEND_PACIENTE_UNIDADE APU ON AP.NR_ATENDIMENTO = APU.NR_ATENDIMENTO
    INNER JOIN TASY.SETOR_ATENDIMENTO SA ON APU.CD_SETOR_ATENDIMENTO = SA.CD_SETOR_ATENDIMENTO
    INNER JOIN TASY.ESTABELECIMENTO ON ESTABELECIMENTO.CD_ESTABELECIMENTO = AP.CD_ESTABELECIMENTO
    INNER JOIN TASY.EMPRESA ON EMPRESA.CD_EMPRESA = ESTABELECIMENTO.CD_EMPRESA
WHERE EMPRESA.CD_EMPRESA = 1 AND ESTABELECIMENTO.CD_ESTABELECIMENTO IN (1, 34) 
AND AP.IE_TIPO_ATENDIMENTO = 3 
AND AP.DT_ENTRADA >= TO_DATE('{data_ini}', 'DD/MM/YYYY')
AND AP.DT_ENTRADA < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY '''

query_evolucao = '''SELECT * FROM TASY.VW_HDATA_EVOLUCAO_PACIENTE WHERE DT_EVOLUCAO >= TO_DATE('{data_ini}', 'DD/MM/YYYY')
AND DT_EVOLUCAO < TO_DATE('{data_fim}', 'DD/MM/YYYY') + INTERVAL '1' DAY '''